/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/7c799834066462e2c64ea4dd16c551c78654b01d293324b813d68ba7e175403f?placeholderIfAbsent=true&apiKey=ab3c43d981ed4dfe8975ab5bc9a48b20"
      alt="VivaMQ Logo"
      className="object-contain self-center max-w-full aspect-[4.65] w-[233px]"
    />
  );
}

export default Logo;
