/**
 * This code was generated by Builder.io.
 */
import React from "react";

function OneIDIndicator() {
  return (
    <div className="flex gap-2 self-center mt-3 text-center whitespace-nowrap text-black text-opacity-40 w-[68px]">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/861893f2a3013c9f355dc24b42cd06e601adfe0292d7b35d402108ccf682c7cb?placeholderIfAbsent=true&apiKey=ab3c43d981ed4dfe8975ab5bc9a48b20"
        alt=""
        className="object-contain shrink-0 w-4 aspect-[0.94]"
      />
      <span className="my-auto">OneID</span>
    </div>
  );
}

export default OneIDIndicator;
