/**
 * This code was generated by Builder.io.
 */
import React from "react";

function VerifyButton() {
  return (
    <button
      type="submit"
      className="px-16 py-5 mt-9 text-base font-medium text-center text-white uppercase whitespace-nowrap bg-red-700 rounded-[166px] max-md:px-5 max-md:mr-1.5 w-full"
    >
      Verify
    </button>
  );
}

export default VerifyButton;
